# Generated by Django 3.2.5 on 2021-07-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_site_slab_level_work_volume_wv_daily_report_details_wv_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='FU_Site_Image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
