# Generated by Django 3.2.5 on 2021-07-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TX_Site_Name', models.CharField(max_length=200)),
                ('Is_Active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slab_Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TX_Slab_Level_Name', models.CharField(max_length=200)),
                ('Is_Active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Work_Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tx_Name', models.CharField(max_length=200)),
                ('Is_Active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WV_Daily_Report_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_WV_Main', models.CharField(max_length=200)),
                ('TX_Panel_No', models.CharField(max_length=200)),
                ('TX_Zone', models.CharField(max_length=200)),
                ('CD_Slab_Level', models.CharField(max_length=200)),
                ('CD_Work', models.CharField(max_length=200)),
                ('TX_Man_Power_Work', models.CharField(max_length=200)),
                ('TX_Sur_Joint', models.CharField(max_length=200)),
                ('PU_Kg', models.CharField(blank=True, max_length=200, null=True)),
                ('PU_PKR', models.CharField(blank=True, max_length=200, null=True)),
                ('Volume_L', models.CharField(blank=True, max_length=200, null=True)),
                ('Volume_W', models.CharField(blank=True, max_length=200, null=True)),
                ('Volume_H', models.CharField(blank=True, max_length=200, null=True)),
                ('Volume', models.CharField(blank=True, max_length=200, null=True)),
                ('AREA', models.CharField(blank=True, max_length=200, null=True)),
                ('Progress', models.CharField(max_length=200)),
                ('Cement', models.CharField(blank=True, max_length=200, null=True)),
                ('Rebar_Qty', models.CharField(blank=True, max_length=200, null=True)),
                ('Rebar_Length', models.CharField(blank=True, max_length=200, null=True)),
                ('Rebar_Size', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('Is_Active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WV_Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CD_Site', models.CharField(max_length=200)),
                ('TX_Site_Supervisor', models.CharField(max_length=200)),
                ('TX_Site_In_charge_Design', models.CharField(max_length=200)),
                ('TX_Site_In_charge_QS', models.CharField(max_length=200)),
                ('TX_Site_Manager', models.CharField(max_length=200)),
                ('TX_Construction_Manager', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('Is_Active', models.BooleanField(default=True)),
            ],
        ),
    ]
