# Generated by Django 3.2.5 on 2021-07-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0003_site_fu_site_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='FU_Site_Image',
            field=models.ImageField(blank=True, null=True, upload_to="upload_to='media/%Y/%m/%d/'"),
        ),
    ]
