# Generated by Django 3.2.4 on 2021-09-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0005_auto_20210717_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TX_Inspection_Status', models.CharField(max_length=200)),
                ('Is_Active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='wv_daily_report_details',
            name='FU_WV_Image',
            field=models.ImageField(blank=True, null=True, upload_to='defect_submission/%Y/%m/%d/'),
        ),
    ]
