# Generated by Django 3.2.4 on 2021-10-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0006_auto_20210901_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TX_Designation_Name', models.CharField(max_length=200)),
                ('Is_Active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DR_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_DR_Main', models.CharField(max_length=200)),
                ('TX_Panel_No_Range', models.CharField(blank=True, max_length=200, null=True)),
                ('Start_Date', models.CharField(blank=True, max_length=200, null=True)),
                ('End_Casting_Concrete', models.CharField(blank=True, max_length=200, null=True)),
                ('Manpower_Classification', models.CharField(blank=True, max_length=200, null=True)),
                ('TX_Designation_No', models.CharField(blank=True, max_length=200, null=True)),
                ('Day_Night', models.CharField(blank=True, max_length=200, null=True)),
                ('CD_Equipment', models.CharField(blank=True, max_length=200, null=True)),
                ('CD_Equipment_Specification', models.CharField(blank=True, max_length=200, null=True)),
                ('TX_Equipment_Qty', models.CharField(blank=True, max_length=200, null=True)),
                ('TX_Equipment_Unit', models.CharField(blank=True, max_length=200, null=True)),
                ('Remark', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('Is_Active', models.BooleanField(default=True)),
                ('FU_WV_Image', models.ImageField(blank=True, null=True, upload_to='defect_submission/%Y/%m/%d/')),
                ('TX_Designation', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('TX_Activity', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('TX_Classification_Name', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TX_Equipment_Name', models.CharField(max_length=200)),
                ('Is_Active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment_Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TX_Equipment_Specification_Name', models.CharField(max_length=200)),
                ('Is_Active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Inspection_Status',
            new_name='Classification',
        ),
        migrations.RenameField(
            model_name='classification',
            old_name='TX_Inspection_Status',
            new_name='TX_Classification_Name',
        ),
    ]
